/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
	import flash.display.Sprite;
	
	
	/**
	 * 
	 * @author larryhou
	 * @createTime Jul 9, 2013 1:12:30 PM
	 */
	public class FlexUnitCompilerApplication extends Sprite
	{
		/**
		 * 构造函数
		 * create a [FlexUnitCompilerApplication] object
		 */
		public function FlexUnitCompilerApplication()
		{
			
		}
	}
}